# Generated by Django 2.0 on 2018-04-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
